apiVersion: apps/v1
kind: Deployment
metadata:
  name: aeroops-db
  labels:
    app: aeroops-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aeroops-db
  template:
    metadata:
      labels:
        app: aeroops-db
    spec:
      containers:
        - name: aeroops-db
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "aeroops_dashboard"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "root"
          volumeMounts:
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: init-sql
          configMap:
            name: aeroops-db-init
---
apiVersion: v1
kind: Service
metadata:
  name: aeroops-db
spec:
  selector:
    app: aeroops-db
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
