spring.application.name=aeroops-dashboard-api
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/aeroops_dashboard
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:root}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=aeroops
spring.jpa.open-in-view=false

management.endpoints.web.exposure.include=health,prometheus
management.endpoint.health.show-details=always
