-- pgAdmin: connect to the aeroops_dashboard database before executing this file.
CREATE SCHEMA IF NOT EXISTS aeroops;
SET search_path TO aeroops;
CREATE TABLE airports (id BIGSERIAL PRIMARY KEY, code VARCHAR(3) UNIQUE NOT NULL, name VARCHAR(120) NOT NULL, city VARCHAR(80) NOT NULL, country VARCHAR(80) NOT NULL);
CREATE TABLE aircraft (id BIGSERIAL PRIMARY KEY, registration VARCHAR(20) UNIQUE NOT NULL, model VARCHAR(80) NOT NULL, seat_capacity INTEGER NOT NULL CHECK(seat_capacity>0), status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE');
CREATE TABLE crew_members (id BIGSERIAL PRIMARY KEY, employee_no VARCHAR(20) UNIQUE NOT NULL, full_name VARCHAR(120) NOT NULL, role VARCHAR(40) NOT NULL, duty_status VARCHAR(20) NOT NULL DEFAULT 'OFF_DUTY');
CREATE TABLE flights (id BIGSERIAL PRIMARY KEY, flight_number VARCHAR(10) NOT NULL, origin VARCHAR(3) NOT NULL REFERENCES airports(code), destination VARCHAR(3) NOT NULL REFERENCES airports(code), gate VARCHAR(10), scheduled_departure TIMESTAMP NOT NULL, aircraft VARCHAR(80) NOT NULL, status VARCHAR(20) NOT NULL CHECK(status IN ('SCHEDULED','BOARDING','DEPARTED','IN_AIR','LANDED','DELAYED','CANCELLED')), passenger_load INTEGER NOT NULL DEFAULT 0 CHECK(passenger_load BETWEEN 0 AND 100));
CREATE TABLE bookings (id BIGSERIAL PRIMARY KEY, booking_ref VARCHAR(12) UNIQUE NOT NULL, flight_id BIGINT NOT NULL REFERENCES flights(id), passenger_name VARCHAR(120) NOT NULL, fare_amount NUMERIC(12,2) NOT NULL, booking_status VARCHAR(20) NOT NULL DEFAULT 'CONFIRMED');
CREATE INDEX idx_flights_departure ON flights(scheduled_departure); CREATE INDEX idx_flights_status ON flights(status);
INSERT INTO airports(code,name,city,country) VALUES ('JFK','John F. Kennedy International','New York','USA'),('LHR','Heathrow','London','UK'),('DXB','Dubai International','Dubai','UAE'),('BOM','Chhatrapati Shivaji Maharaj International','Mumbai','India'),('CDG','Charles de Gaulle','Paris','France'),('NRT','Narita International','Tokyo','Japan');
INSERT INTO aircraft(registration,model,seat_capacity) VALUES ('VT-AIA','Boeing 787-9',296),('VT-AIB','Airbus A350-900',316),('VT-AIC','Boeing 777-300ER',342);
INSERT INTO crew_members(employee_no,full_name,role,duty_status) VALUES ('CR-001','Sarah Johnson','Flight Commander','ON_DUTY'),('CR-002','Michael Chen','First Officer','ON_DUTY'),('CR-003','Emma Davis','Cabin Manager','ON_DUTY');
INSERT INTO flights(flight_number,origin,destination,gate,scheduled_departure,aircraft,status,passenger_load) VALUES ('AI 217','JFK','LHR','A12',CURRENT_DATE + TIME '08:45','Boeing 787','BOARDING',74),('AI 305','DXB','BOM','B07',CURRENT_DATE + TIME '09:30','Boeing 787-9','DEPARTED',92),('AI 402','CDG','JFK','A09',CURRENT_DATE + TIME '10:05','Airbus A350','DELAYED',88),('AI 777','JFK','NRT','B11',CURRENT_DATE + TIME '12:20','Boeing 777-300ER','IN_AIR',34);
INSERT INTO bookings(booking_ref,flight_id,passenger_name,fare_amount) VALUES ('AOP-8FD12',1,'Olivia Martin',1240.00),('AOP-1MK93',2,'Arjun Mehta',760.00),('AOP-7QZ41',3,'Nora Dubois',1580.00),('AOP-5TP28',4,'Kenji Sato',1940.00);
